### ISSUE TITLE
Mobile scroll

### ISSUE THREAD

**Issue by radugr** [appium/perl-client#9]
Hello,

I need to be able to scroll within a mobile app. Tried using some combination of taping and move_to, and also sending "mobile: scrollTo" using execute_script. Both yield "not implemented". Are there any plans to implement this? Or is there another way to scroll in Android&iOS apps that I'm not aware of?

I would gladly contribute to the project, but I've just started using this and I'm not completely sure how to do some stuff, so my knowledge isn't up to the task of contributing just yet.

Thanks,
-Radu

**Comment by gempesaw** [comment]
Hmmmmmm ... you are correct, it's not currently implemented in the perl client right now. Having read some docs, looks like it'll definitely be possible, especially thanks to gempesaw/Selenium-Remote-Driver#204. 

If you're in a big hurry, `execute_script` is probably the way to go and I think probably what my efforts will boil down to, but otherwise I should be able to take a look tonight or tomorrow night.

possibly helpful links for me to find later:

- https://github.com/appium/perl-client/blob/master/lib/Appium/TouchActions.pm
- https://github.com/appium/python-client/blob/master/appium/webdriver/webdriver.py
- https://github.com/appium/appium/blob/master/lib/server/routing.js#L58
- https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md

**Comment by gempesaw** [comment]
@radugr 

- are you trying to do this on iOS or Android? or, hm, both?
- is the following what you tried ? does it work/not work? or, what did you try to do ?

    ```perl
    $appium->execute_script(
        'mobile: scroll',
        { direction => 'down' }
    );
    ```

- do you care about scrolling a particular element, or just scrolling the entire screen in general?

**Comment by radugr** [comment]
@gempesaw 

* I'm working on both.

First let me explain how my app looks like so you understand what I need scrolling for. One of the screens is a collection of list views. Both the collection and the list view items expand beyond the screen, so they are both scrollable. On the Android version, the collections are displayed horizontally (so I need to scroll down to see all collections and scroll right to see all elements from a collection). On the iOS version, the collections are displayed vertically (so I need to scroll right to see all collections and scroll down to see all elements from a collection).

* Initially I tried with 'mobile: scrollTo' to scroll to a certain element and it yielded 'not implemented'. Now I tried with scroll (your code snippet). Here's what happened:
  * On iOS - ran your code snippet with direction "right" and it works (it scrolls exactly 1 screen to the right)
  * On Android - ran your code snippet with direction "down" and get this error returned to the calling script: 

>Can't use string ("ERROR running Appium command: st") as a HASH ref while "strict refs" in use at /usr/local/share/perl5/Appium/ErrorHandler.pm line 12.
 at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 300.

And Appium log:
>info: --> POST /wd/hub/session/df5dec94-ae12-4311-ae16-a7f114c3fa07/execute {"script":"mobile: scroll","args":[{"direction":"down"}]}
info: <-- POST /wd/hub/session/df5dec94-ae12-4311-ae16-a7f114c3fa07/execute 500 1.058 ms - 78 
TypeError: string is not a function
    at [object Object].androidController.scroll (/usr/local/lib/node_modules/appium/lib/devices/android/android-controller.js:691:3)
    at Object.exports.mobileScroll [as scroll] (/usr/local/lib/node_modules/appium/lib/server/controller.js:645:14)
    at Object.exports.executeMobileMethod (/usr/local/lib/node_modules/appium/lib/server/controller.js:984:22)
    at exports.execute (/usr/local/lib/node_modules/appium/lib/server/controller.js:940:15)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:267:22
    at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:340:14)
    at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:356:14)
    at Function.proto.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:400:3)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:261:10)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:100:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at exports.sessionBeforeFilter (/usr/local/lib/node_modules/appium/lib/server/controller.js:56:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)

* I care about both, I need to scroll the entire screen to see all the collections and also scroll in a particular collection to see all the items.

Thank you for your help!
-Radu
